### PR TITLE
BUGFIX - TYPO3-11 Site-View

### PR DESCRIPTION
**Pull request by ghost**
Sobald das Plug-In eingebaut ist und man in der TYPO3 auf die Web->Seite Darstellung schaltet erhalten wir einen Fehler durch die u.g. Methode. Daher hab ich den Part erstmal ausgeblendet, damit funktioniert alles wieder problemlos. Der Part sollte zukünftig überarbeitet werden. Danke für den Pull im Voraus.

### CODE REVIEW

**Comment by Teisi** [comment]
Thank you for your report!

Can you also tell us how to reproduce this behavior?
Which TYPO3 version?
Which PHP version?
Which error message?
Configuration of your slider?
Content elements?
Images? Or files from a folder? etc. etc.

Best you open an "Issue" for a pull-request at the same time :)

Thank you!

------

And please report issues in english, so everyone can benefit from it, thanks ;)

**Comment by ghost** [comment]
Hi Teisi

Can you also tell us how to reproduce this behavior?
- Only installed on the current TYPO3 Version

Which TYPO3 version?
- 11.5.9

Which PHP version?
-  7.4

Which error message?
- I see the following error message on the page tab
- https://pastebin.com/WTFSNB78
- You can fix it if you uncomment the line 75

Configuration of your slider?
- Only linked in TS, nothing special

Content elements?
Images? Or files from a folder? etc. etc.

**Comment by Teisi** [comment]
hmm so I can't reproduce this directly and actually the error message already says the "error":
"Tried resolving a template file for controller action "Standard->index" in format ".html", but none of the paths contained the expected template file (Standard/Index.html). No paths configured."

I think this means it is missing the paths to the HTML template / partial / layout files.
This means either missing TypoScript or PageTs (by default you have to import both with the HauerHeinrich Extensions) or maybe the corresponding parts were overwritten.

Would you like to check this, please? :)

BTW, an out commenting code, is rarely a "bug" fix :)
So if I would like to be able to track that, so we can really fix that without limiting functionalities or something like that. ;)

**Comment by ghost** [comment]
Strange... I cleaned all temporary files and reEnable the Plugin and now it's gone.... only for a while

**UPDATE: Again....**
Same error...

I will your check your idea...

> I think this means it is missing the paths to the HTML template / partial / layout files.
This means either missing TypoScript or PageTs (by default you have to import both with the HauerHeinrich Extensions) or maybe the corresponding parts were overwritten.
Would you like to check this, please? :)

**Comment by ghost** [comment]
Ok. Checked ... Same problem.
I get the same error on a completly different system again.

```
InvalidTemplateResourceException
Tried resolving a template file for controller action "Standard->hhSlider" in format ".html", but none of the paths contained the expected template file (Standard/HhSlider.html). No paths configured.

```
Currently, i need to comment the one line to fix it. 
/var/www/htdocs/typo3conf/ext/hh_slider/Classes/Hooks/PageLayoutViewDrawItem.php line 63

```
...
#$itemContent = $this->view->render();
...
```

**Comment by Teisi** [comment]
I have now had time to look at this again, I still can't fully comprehend it. Nevertheless, I have now decided to check whether the "newer" method for the CE backend preview would not be possible instead of the hook.
I find at the moment still something stupid, but let's see... :D

https://docs.typo3.org/c/typo3/cms-core/main/en-us/Changelog/10.3/Feature-78450-IntroducePreviewRendererPattern.html

**Pull request closed without merging**
